### 2. Basic Array Operations

In [ ]:
import numpy as np

In [ ]:
a = np.array([5, 6, 7])

print(f"a[0]: {a[0]}")
print(f"a.ndim: {a.ndim}")
print(f"a.dtype: {a.dtype}")
print(f"a.itemsize: {a.itemsize}")
print(f"a.size: {a.size}")
print(f"a.shape: {a.shape}")

a[0]: 5
a.ndim: 1
a.dtype: int32
a.itemsize: 4
a.size: 3
a.shape: (3,)


In [70]:
b = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
], dtype=np.float64)

print(f"b[0]: {b[0]}")
print(f"b.ndim: {b.ndim}")
print(f"b.dtype: {b.dtype}")
print(f"b.itemsize: {b.itemsize}")
print(f"b.size: {b.size}")
print(f"b.shape: {b.shape}")

b[0]: [1. 2.]
b.ndim: 2
b.dtype: float64
b.itemsize: 8
b.size: 6
b.shape: (3, 2)


In [71]:
c = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[1, 2], [3, 4], [5, 6]]
], dtype='U10')

print(f"c[0]: {c[0]}")
print(f"c.ndim: {c.ndim}")
print(f"c.dtype: {c.dtype}")
print(f"c.itemsize: {c.itemsize}")
print(f"c.size: {c.size}")
print(f"c.shape: {c.shape}")


c[0]: [['1' '2']
 ['3' '4']
 ['5' '6']]
c.ndim: 3
c.dtype: <U10
c.itemsize: 40
c.size: 12
c.shape: (2, 3, 2)


--------------------

if you want to initialize your array with placeholder numbers 

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

-----------------------------------

np arrange is similar to python range

In [ ]:
l=range(5)
l

range(0, 5)


In [77]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(0,5,2) # steps of 2

array([0, 2, 4])

linspace function # linear sequence of evenly spaced numbers

In [82]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

reshape

In [84]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [89]:
b.reshape(2,3)  # doesnt make changes to the original array

array([[1., 2., 3.],
       [4., 5., 6.]])

ravel # flatten to one dimensional array

In [87]:
b.ravel() # this will not touch the original array it will return a new array

array([1., 2., 3., 4., 5., 6.])

In [88]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### math functions

In [90]:
b.min()

1.0

In [91]:
b.max()

6.0

In [92]:
b.sum()

21.0

In [ ]:
b.sum(axis=0) # axis=0 means you're summing along the vertical direction 

array([ 9., 12.])

In [ ]:
b.sum(axis=1) # axis=1 means you're summing along the horizondal direction 

array([ 3.,  7., 11.])

In [95]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [97]:
np.std(b)

1.707825127659933

### math operations

In [98]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [99]:
a+b

array([[ 6,  8],
       [10, 12]])

In [100]:
a-b

array([[-4, -4],
       [-4, -4]])

In [101]:
a*b

array([[ 5, 12],
       [21, 32]])

In [102]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [103]:
a.dot(b)

array([[19, 22],
       [43, 50]])