### 3. slicing/stacking arrays, indexing with boolean arrays

In [1]:
import numpy as np

In [2]:
# list
n=[6,7,8]
print(n[0:2])
print(n[-1])

[6, 7]
8


In [3]:
# same for numpy array
a= np.array([6,7,8])
print(a[0:2])
print(a[-1])

[6 7]
8


-------------------------------

In [52]:
a= np.array([[6,7,8],[1,2,3],[9,3,2]])

In [ ]:
a[1,2] # preferred -- and this doesnt work with lists 

3

In [ ]:
a[1][2] # not preferred coz it first extract antire [1] and then selects [2]

3

In [9]:
a[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [8]:
a[0:2,2]

array([8, 3])

In [10]:
a[-1]

array([9, 3, 2])

In [54]:
a[-1,:2]

array([9, 3])

In [17]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

print 723, 832

In [16]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

-----------------------

### iterate through arrays

In [18]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [19]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


to print all the cells numpy has a flat method

In [20]:
for cell in a.flat:
    print(cell)


6
7
8
1
2
3
9
3
2


-------------

sticking two arrays together

In [22]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

-----------------------

splitting arrays

In [27]:
ar = np.arange(30).reshape(2,15)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
np.hsplit(ar,3) # 3 and 5 woks, 2,4,6 doesnt so it must exactly be divisible

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [40]:
np.vsplit(ar,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

-----------

indexing with boolea array

In [45]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [50]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])